name: sun_fo_timer
description: 'A new Flutter project.'
publish_to: 'none'

# rive animation update
version: 1.0.3+1

environment:
    sdk: '>=3.2.6 <4.0.0'

dependencies:
    flutter:
        sdk: flutter
    rive:
    freezed_annotation:
    json_annotation:
    shared_preferences:

    cupertino_icons: ^1.0.2
    wakelock_plus: ^1.1.6
    screen_brightness: ^1.0.0
    hooks_riverpod:
    riverpod_annotation:
    flutter_hooks:
    mockito:

dev_dependencies:
    flutter_test:
        sdk: flutter
    build_runner:
    riverpod_generator:
    freezed:
    json_serializable:
    flutter_launcher_icons:

    flutter_lints: ^2.0.0

flutter:
    fonts:
        - family: Kiwi_Maru
          fonts:
              - asset: assets/fonts/Kiwi_Maru/KiwiMaru-Regular.ttf
                weight: 500
              - asset: assets/fonts/Kiwi_Maru/KiwiMaru-Medium.ttf
                weight: 400
              - asset: assets/fonts/Kiwi_Maru/KiwiMaru-Light.ttf
                weight: 300

    uses-material-design: true

    assets:
        - assets/images/
        - assets/rive/

flutter_launcher_icons:
    android: false
    ios: false
    image_path: 'assets/images/icon_android.png'
    min_sdk_android: 21 # android min sdk min:16, default 21
    adaptive_icon_background: '#41445A'
    adaptive_icon_foreground: 'assets/images/icon_android.png'
    macos:
        generate: true
        image_path: 'assets/images/icon_ios.png'
